version: "3"
volumes:
  db_final_data:
services:
  db:
    image: postgres:17
    container_name: db_final
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
    volumes:
      - ./db_final.sql:/docker-entrypoint-initdb.d/1-db_final.sql
      - db_final_data:/var/lib/postgresql/data
    expose:
      - 5500
    ports:
      - "5500:5500"
  pgadmin:
    container_name: pgadmin4practicaFinal
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - "./pgadmin/pgadmin_servers.json:/pgadmin4/servers.json"
      - "./pgadmin/pgadmin_pass:/pgadmin4/pass"
    ports:
      - "5052:80"
